### ISSUE TITLE
Mensaje de validación de correo electrónico

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#111]
Este mensaje es para verificar el correo electrónico que usted registró en el Sistema de Gestión Escolar del Posgrado en Ciencias de la Sostenibilidad. Para confirmarlo favor de hacer clic en la siguiente liga: https://sostenibilidad.posgrado.unam.mx/siges/accounts/confirm-email/MjI:1fxEux:Ru0mUKhctWE3AfGUw851Fr_ybgE/

Gracias por su atención.
Saludos cordiales,
La Coordiación

**Comment by rgarcia-herrera** [comment]
ca414b4
