### ISSUE TITLE
PRIDE

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#112]
Incluir una categoría que se llama Estímulo por Equivalencia

**Comment by majosesolares** [comment]
El campo PRIDE deberá llamarse estímulo UNAM. Deberá incluir una opción por cada nivel y por cada estímulo. Ver liga Marisa.

Agregar documento probatorio

**Comment by rgarcia-herrera** [comment]
c3d5a9e

**Comment by rgarcia-herrera** [comment]
c3d5a9e

**Comment by rgarcia-herrera** [comment]
d0db318
