### ISSUE TITLE
En tabla de estudiantes 

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#121]
Cambiar folio de título por folio de acta de examen de grado 
Cambiar fecha de titulación por fecha de graduación
Mayúsculas en Alfonso Caso

En semestre de graduación indicar con un ejemplo como debe llenarse:
Registrar el semestre escolar. Ejemplo 2018-2

Cambiar institución por institución de inscripción y mover el campo al principio del formulario. Solo dejar las opciones de las doce entidades del PCS

**Comment by rgarcia-herrera** [comment]
d5a2872
