### ISSUE TITLE
CURP y RFC - Adscripcion - Foto

### ISSUE THREAD

**Issue by mofuss** [pcs-unam/siges#122]
Aunque seamos extranjeros la mayoría tenemos CURP y RFC porque son necesarios para ser contratados en la UNAM. No es muy claro.

Hay una lista limitada de adscripciones, no pude agregar la mía: UNAM, Centro de de Investigaciones en Geografía Ambiental

La foto no parece cargar bien (usando Chrome al menos).

**Comment by majosesolares** [comment]
Cambiar la redacción en CURP y RFC:
 Si usted es extranjero(a) y no cuenta con CURP, ingresar la palabra extranjero(a)*

**Comment by majosesolares** [comment]
Se abrió el issue #130 para resolver lo de la foto

**Comment by majosesolares** [comment]
Si se puede agregar una nueva institución haciendo clic en "agregar institución a la lista" que aparece debajo de la lista de instituciones. Para agregar la asociación a una entidad del PCS se abrió el issue #128, ya que si se detectó una falla.

**Comment by rgarcia-herrera** [comment]
6099089
