### ISSUE TITLE
Otros programas en los que participa como tutor principal (o miembro de comité tutor)

### ISSUE THREAD

**Issue by mofuss** [pcs-unam/siges#123]
Se deben listar los programas independientemente si en este momento se cuenta con alumnos vigentes? En mi caso por ejemplo estoy acreditado como tutor de doctorado y maestría en ciencias biológicas pero ya concluyeron sus estudios y en este momento no tengo alumnos vigentes. Pero sigo acreditado claro está.

**Comment by majosesolares** [comment]
Sí se debe mencionar el programa si forma parte del padrón de tutores.

**Comment by majosesolares** [comment]
Solo se deben registrar los programas en los que participa actualmente como miembro de comité tutor o como tutor principal. Esta pregunta busca conocer la carga de trabajo en cuanto asesoría de alumnos en otros posgrado.
