### ISSUE TITLE
Agregar campos en tabla de académicos

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#126]
Cambiar de "Otros programas en los que participa como miembro de comité tutor" por "Nombres de los otros programas en los que participa como miembro de comité tutor"

Item para tutor principal

Cantidad total de participaciones como miembro de comité tutor (no tutor principal) de estudiantes graduados de nivel maestría 

Cantidad total de participaciones como miembro de comité tutor (no tutor principal) de estudiantes graduados de nivel doctorado

Cambiar en todos los casos que diga "tesis dirigidas y concluidas" por: "de participaciones como tutor principal de estudiantes graduados de nivel....... (para licenciatura se debe poner titulados y para M y D graduados)

1.    Si su productividad académica no se ve reflejada en las publicaciones anteriores, indique si cuenta con otros productos como por ejemplo informes técnicos, memorias técnicas, desarrollo de proyectos hasta nivel ejecutivo, planes y programas de desarrollo urbano, manuales, etc.

2.    Si no cuenta con estudiantes graduados, indique si cuenta con otras actividades académicas como por ejemplo estancias de investigación, seminarios de titulación, etc.

Cuenta con experiencia docente avalada por la impartición de al menos una asignatura o actividad académica en los últimos tres años (campo booleano).

**Comment by majosesolares** [comment]
Sustituir PCS por Posgrado en Ciencias de la Sostenibilidad

**Comment by majosesolares** [comment]
Todas las preguntas relacionadas con el PCS poner paréntesis (sólo llenar en caso de reacreditación)

**Comment by rgarcia-herrera** [comment]
b1d460e
