### ISSUE TITLE
¿Cómo se notificará a las personas que envíen solicitud la resolución del Comité Académico?

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#136]
Particularmente pensar en el procedimiento de los no acreditados.

**Comment by majosesolares** [comment]
Hacer un expediente en el perfil personal  donde se puedan anexar documentos. Ahí anexaríamos la carta de acreditación para que ellos la descarguen. Con esto listo se puede enviar un correo pidiendo que entren al sistema para conocer la decisión del Comité Académico

**Comment by rgarcia-herrera** [comment]
ab34134
