### ISSUE TITLE
Para la acreditación sería importante preguntar si se tiene interés en acreditarse para un alumno en específico o en general para otros aspirantes o alumnos del Posgrado

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#137]

**Comment by majosesolares** [comment]
Estaría usted interesado en formar parte de la plantilla pública de tutores del Posgrado para que los aspirantes y alumnos puedan contactarlo y solicitar su asesoría. En ese caso favor de especificar su disponibilidad:

**Comment by rgarcia-herrera** [comment]
6bbf223
