### ISSUE TITLE
Quitar "en otros programas"

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#141]
Cantidad total de participaciones como miembro de comité tutor (no tutor principal) de estudiantes graduados de nivel doctorado en otros programas.

Quitar campo
Nombres de los otros programas en los que participa como miembro de comité tutor (no tutor principal)

Cambiar campo que dice Nombres de los otros programas en los que participa como tutor principal por
Nombres de los programas de posgrado en los que participa

**Comment by rgarcia-herrera** [comment]
61a8f17
