### ISSUE TITLE
En la tabla de cursos sustituir campo de profesores y contactos por liga a la tabla de ususarios

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#167]

**Comment by rgarcia-herrera** [comment]
Este issue hay que cerrar sólo al final del semestre actual. Mientras tanto los datos de los campos de profesores y contactos son los que se despliegan en la página web.

Terminado el semestre se podrán eliminar de manera permanente esos campos. Mientras tanto son de sólo-lectura.
