### ISSUE TITLE
Admin registra profesores

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#168]
Los registra con nombre y correo

**Comment by majosesolares** [comment]
Profesores recién registrados tienen el estatus de candidato

**Comment by rgarcia-herrera** [comment]
# Modelo de profesor
 - fecha de alta
 - campo de conocimiento
 - Las opciones para acreditación son: candidato, no-acreditado, baja, profesor

del prototipo quitar:
 - fecha de reacreditación
 - líneas de investigación
