### ISSUE TITLE
En acreditación incluir una categoría más que sea "información incompleta"

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#181]

**Comment by rgarcia-herrera** [comment]
"información incompleta" se incluirá como estado posible para un académico, junto con los estados de acreditación M, D, E y "no acreditado" y "baja".

Además incluiremos:
"descalificado" para quienes no cumplen los [requisitos](https://github.com/sostenibilidad-unam/posgrado/files/2645942/Requisitos.acreditacion.pdf).

**Comment by rgarcia-herrera** [comment]
Además incluir:
'por reacreditar M'
'por reacreditar D'
'por reacreditar E'

**Comment by majosesolares** [comment]
Descalificado es no acreditado
