### ISSUE TITLE
Corregir orden alfabético de apellidos tutores porque minúsculas y acentos los manda al final

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#188]
Por ejemplo Ávila y del Val.
Issue no tan urgente pero necesario.

**Comment by rgarcia-herrera** [comment]
https://stackoverflow.com/questions/1097908/how-do-i-sort-unicode-strings-alphabetically-in-python

**Comment by rgarcia-herrera** [comment]
https://docs.djangoproject.com/en/3.1/ref/models/options/#ordering

Al parecer se puede usar un tipo de filtro en el campo ordering de la clase meta del modelo. Está peliagudo :-/
