### ISSUE TITLE
Crear cargador de info estudiantes desde Genovevita

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#208]
Esto se hará sólo una vez

**Comment by rgarcia-herrera** [comment]
https://sostenibilidad.posgrado.unam.mx/siges/admin/posgradmin/estudios/1646/change/

**Comment by rgarcia-herrera** [comment]
Aqui tenemos el [perfil de la estudiante](https://sostenibilidad.posgrado.unam.mx/siges/admin/posgradmin/estudios/1646/change/) y necesitamos actualizarlo para poder cerrar este issue.
