### ISSUE TITLE
Importar el campo de conocimiento o línea de inv. en la tabla de estudios

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#220]

**Comment by rgarcia-herrera** [comment]
Aqui una descripción

**Comment by rgarcia-herrera** [comment]
> Aqui una descripción

Aquí una respuesta.

**Comment by rgarcia-herrera** [comment]
Vamos a crear una tabla de proyectos. En esa tabla se vinculan campos de conocimiento y líneas de investigación a los estudiantes.
