### ISSUE TITLE
exportar plan desde genoveva

### ISSUE THREAD

**Issue by carocyborg** [pcs-unam/siges#223]
este es mi primer issue

**Comment by rgarcia-herrera** [comment]
Para actualizar el programa de los estudios hay que exportar desde genoveva:

- año
- semestre
- plan
- cuenta de estudiante

**Comment by carocyborg** [comment]
solicitar un nuevo respaldo de SAEP

**Comment by rgarcia-herrera** [comment]
Al importar, el estado será "inscrita" y la fecha será "primero de agosto"
