### ISSUE TITLE
Constancias desde la página del curso donde los profesores las generan para estudiantes externos a la UNAM

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#227]
Redacción: 
Por medio de la presente se hace constar que ______ cursó la asignatura “______”, obteniendo una calificación final de ______. El curso forma parte de la Maestría en Ciencias de la Sostenibilidad de la Universidad Nacional Autónoma de México. Dicho curso fue impartido durante el semestre _____, con un total de ____ horas, equivalente a ____ créditos.

Firma el(la) profesor(a) del curso

**Comment by rgarcia-herrera** [comment]
No hay horas en ninguna tabla. También hay cursos con cero créditos ¿cómo reportamos esos?
