### ISSUE TITLE
Exportar estados desde genovevita

### ISSUE THREAD

**Issue by carocyborg** [pcs-unam/siges#233]
tabla alumnos: cuenta + correo + fecha (solo año) + beca (si hay medalla) + entidad

**Comment by rgarcia-herrera** [comment]
Agregar también una columna con el estado. Estados posibles son:
 - inscrito
 - egresado
 - graduado
 - indeterminado
 - baja
 - suspension 1
 - suspension 2
 - plazo adicional

Estos son los estados del SIGES. Si no están en Genovevita, poner los equivalentes. Si no se llaman nomás apuntar acá en un comentario cuál va con cuál, para transformarlos a la hora de cargarlos.
