### ISSUE TITLE
Apoyo de proceso de estancia PAEP

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#236]
Datos formulario:

 - Tipo de actividad (curso, congreso o estancia)
 - Nombre de la actividad
 - Fecha de inicio de la actividad
 - Fecha de fin de la actividad
 - País
 - Ciudad
 - Institución 

Info que no se pide a lxs alumnxs
 - Monto otorgado
 - Fecha de solicitud

**Comment by rgarcia-herrera** [comment]
Agregar campo "producto" que permita anexar un archivo, que podrá ser un reporte o un informe u otro documento.

**Comment by rgarcia-herrera** [comment]
Agregar campo de estado. Estados posibles son:
- solicitado
- otorgado
- rechazado
- concluido
- sin producto

Desarrollar algoritmo que marque estancias otorgadas como sin producto si han pasado treinta días naturales tras la fecha de terminación, y no se ha anexado producto.
