### ISSUE TITLE
Crear tabla de actividades académicas complementarias

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#248]
Revisar el formato en https://sostenibilidad.posgrado.unam.mx/assets/formatos/doctorado/formato-actividades-academicas-complementarias.xlsx

Esta tabla tendrá un campo para conocer el estado en el proceso.
El tutor principal cambia el estado a autorizado después de que el alumno lo registra.
Los alumnos suben un el acta de evaluación. 
Una idea es que el mismo tutor revise al estudiante para aprobarlo. Por lo pronto la Coordinación revisa y cierra el proceso.

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/3
