### ISSUE TITLE
Nuevo curso para la Maestría en Ciencias de la Sostenibilidad

### ISSUE THREAD

**Issue by jmmechepo** [pcs-unam/siges#251]
Estimados, quiero registrar un nuevo curso para el Posgrado en Ciencias de la Sostenibilidad titulado " Introducción a la Ciencia de Redes: aplicaciones a sistemas biológicos, económicos y sociales" para el semestre 2023-I. No se donde puedo subir el temario para que los alumnos puedan consultarlo y si ya con este registro queda formalizada la propuesta y los alumnos pueden inscribirse o si hay que hacer alguna otra gestión para esto.

Saludos cordiales.
[CURSO DE REDES_2023.pdf](https://github.com/pcs-unam/siges/files/8657540/CURSO.DE.REDES_2023.pdf)

**Comment by rgarcia-herrera** [comment]
Estimado José Manuel, 

Su solicitud de registro probablemente no ha sido tomada en cuenta pues en este repositorio le damos seguimiento sólo a asuntos relacionados con el desarrollo de la app.

Para temas relacionados con la gestión del programa debe dirigirse a la Coordinación.

Saludos atentos,

Rodrigo García
