### ISSUE TITLE
Diseñar propuesta de estado de rezago

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#261]
Considerar fechas esperadas a partir de primera inscripción y diferencia de tiempo (bandera de rezago esperado o no esperado)

**Comment by majosesolares** [comment]
Sólo hay tres razones por las cuales un estudiante se rezaga: 
pide suspensión de 1 o 2 semestres
reprueba (puedes no darte cuenta)
no se reinscribe

**Comment by majosesolares** [comment]
[tabla posibles estados de estudiantes.xlsx](https://github.com/pcs-unam/siges/files/8930791/tabla.posibles.estados.de.estudiantes.xlsx)

**Comment by majosesolares** [comment]
Después de inscripciones y después del periodo de altas y bajas (aproximadamente a finales de agosto o finales de febrero respectivamente) se puede exportar del SIAEP la tabla de ingreso y reingreso para importar a SIGES. Esta importación se va a requerir cada semestre. En los semestres nones, esta tabla identifica a los inscritos de nuevo ingreso y reinscritos. 
En agosto de cada año (cuando hay nuevo ingreso) se va a utilizar la tabla de aspirantes que debe enviarnos DGAE. Esta última información la debe enviar DGAE después de inscripciones, ya que los aspirantes aceptados se inscribieron.  Esto para que no nos manden la información de los rechazados o aspirantes aceptados que no se inscribieron.

**Comment by majosesolares** [comment]
Para el estado inscrito, incluir el número consecutivo de semestre. Por ejemplo, la primera vez que que un estudiante se registra como inscrito, su estado será inscrito sem 1. La primera reinscripción, aunque ocurra años después, marcará inscrito sem 2, y así consecutivamente.

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/4
