### ISSUE TITLE
En asignaturas agregar la información del semestre en que se propuso

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#266]
Si un curso se propone y aparece como solicitado pero no se aprueba ni se rechaza, tendría que diferenciarse de las propuestas de otros semestres. Se me ocurre que sea con el semestre de convocatoria o incluyendo otro estado como pendiente.

**Comment by rgarcia-herrera** [comment]
Preservar esas fechas como **notas** vinculadas a la asignatura.

**Comment by rgarcia-herrera** [comment]
Esta información se guarda en el histórico de versiones de la tabla.
