### ISSUE TITLE
Agregar columna de institución en tabla de historial desde la vista de estudiante

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#285]
Desplegar siglas:
ENES-León
ENES-Morelia
IEcol
IIngen
IIES
IIEcon
IISociales
ICMyL
IBiol
Fac-Arq
Fac-Ciencias
IER

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/8
