### ISSUE TITLE
Nueva tabla de candidaturas para Doctorado

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#288]
Esta tabla debe registrar:
1. estudiante
2. estado del registro de la candidatura (jurado solicitado, visto bueno comité tutor, aprobado, aprobado con observaciones o rechazado).
3. Asistente del proceso de PCS registra la fecha del exámen, necesaria para el acta
4. Asistente del proceso anota si el examen se aprobó en la primer oportunidad, si no, anotar que pasa a segunda oportunidad y anotar fecha límite para presentarla.
5. Si alguien debe presentar en segunda oportunidad se repite el proceso a partir del punto 3, ya que la asignación de jurado es la misma.
6.  Asistente del proceso anota si el examen en segunda oportunidad se aprobó

# Cartas en el asunto

1. Tras registrar la solicitud del examen se debe poder generar un pdf (editable) con la información de la solicitud para recabar las firmas del comité tutor.

2. Tras aprobar un jurado se debe generar un pdf con la carta de asignación del jurado

3. Tras registrar la fecha se genera el acta (pdf editable para anotar hora, observaciones y firmas jurado)

4. Tras aprobar el examen se genera una carta de candidatura

**Comment by majosesolares** [comment]
El jurado incluye gente que no está acreditada como acadeémico en el siges, de ellos debe registrarse el nombre completo. Académicos acreditados se vinculan a la tabla de académicos.

En algún historial de tutores queda el registro de su participación en jurados.

**Comment by majosesolares** [comment]
En la constancia que se emite para los miembros de jurado, debe poder distinguirse cuál fue su rol en el jurado. 
Son tres roles: Presidente(a), Secretario(a) y Miembro

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/18
