### ISSUE TITLE
vista previa y ejmplo para el campo del prof invitado y ejemplo en el texto de ayuda para el campo prof invitado

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#304]

**Comment by rgarcia-herrera** [comment]
Vista previa para que el usuario pueda corregir.

Ejemplo para el campo del prof invitado en el texto de ayuda.

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/11
