### ISSUE TITLE
Diseñar formato de importación de proyectos

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#307]

**Comment by rgarcia-herrera** [comment]
Un lugar donde puedan decir si su proyecto tienen alguna vinculación con el sector gubernamental, sector privado u organizaciones sociales. En caso de que si exista la vinculación, un espacio donde expliquen. Ver  #158

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/12
