### ISSUE TITLE
Establecer tipos de membresía de comités

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#317]
Tutor(a) principal de Doctorado (TPD)
Cotutor(a) de Doctorado (CD)
Miembro de comité de Doctorado (MCD)

Tutor(a) principal de Maestría (TPM)
Cotutor(a) de Maestría (CM)
Miembro de comité de Maestría (MCM)

**Comment by rgarcia-herrera** [comment]
('M', 'miembro de comité de doctorado'),  # MCD
            ('T', 'tutor de doctorado'),  # TPD

            ('A', 'tutor de maestría'),   # TPM
            ('X', 'miembro de comité de maestría'),  # MCM
            ('Y', 'segundo tutor de maestría'),  # CM
            ('Z', 'tutor principal de maestría')))   # TPM

**Comment by rgarcia-herrera** [comment]
Este issue puede esperar a que se haga la Gran Importación. Ver issue #306
