### ISSUE TITLE
En académicos quitar la entidad de asociación

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#328]
Revisar cómo plantear la pregunta de adscripción de tal manera que evitemos que pongan información incorrecta

**Comment by rgarcia-herrera** [comment]
Quitar checkbox de asociación de la tabla de adscripciones. Una adscripción es un vínculo entre una Institución y un perfil personal.

Por otro lado hay que vincular la tabla de académicos con la tabla de instituciones entidades del pcs. Este vínculo se nombrará: Asociación, y vincula Entidades PCS con Perfiles Académicos.

Este vínculo no se interroga a los académicos, sino que lo llena el administrador.

**Comment by rgarcia-herrera** [comment]
https://codeberg.org/rgarcia-herrera/siges/issues/13
