### ISSUE TITLE
nombres de integrantes de comités para candidatura, grado y comité tutoral

### ISSUE THREAD

**Issue by rgarcia-herrera** [pcs-unam/siges#53]

**Comment by ldelgadobarreto** [comment]
- Tutor Principal

- Cotutor

- Miembro del comité

**Comment by rgarcia-herrera** [comment]
5 integrantes del comité

# candidatura
 - presidente
 - secretario
 - miembro de jurado

# jurado de grado
 - presidente
 - secretario
 - vocal
 - suplente
