### ISSUE TITLE
Error al momento de actualizar mi perfil

### ISSUE THREAD

**Issue by angie-rodriguez** [pcs-unam/siges#66]
https://sostenibilidad.posgrado.unam.mx/siges/inicio/perfil/editar Cuando lleno todos los cambos y le doy en guardar me aparece un error y no se guardan mis datos

![error](https://user-images.githubusercontent.com/39629302/40556598-e1174b78-6012-11e8-8092-3ba0aae2613e.png)

**Comment by majosesolares** [comment]
Me pasó lo mismo.

**Comment by angie-rodriguez** [comment]
En la fecha de nacimiento no lo puse completo y por eso me salía el error, sorry. Ya se guardaron mis datos :)

**Comment by rgarcia-herrera** [comment]
Fecha como tres drop-downs.
