### ISSUE TITLE
campos adicionales a tabla de académicos

### ISSUE THREAD

**Issue by rgarcia-herrera** [pcs-unam/siges#69]
Para dar soporte al proceso de re-acreditación, hay que agregar estos campos:

# Datos personales
 - Pasaporte, para extranjeros

# Resumen Curricular
 - Tesis dirigidas
   - licenciatura
   - maestría
   - doctorado
 - En los últimos 5 años
   - licenciatura
   - maestría
   - licenciatura
 - Tutor Principal
   - maestría
   - doctorado
 - Miembro de Comité Tutor
   - maestría
   - doctorado
 - Artículos publicados en revistas internacionales
 - Artículos publicados en revistas nacionales
 - Artículos internacionales en los últimos 5 años
 - Artículos nacionales en los últimos 5 años
 - Participación como tutor en otros programas
 - Participación como tutor principal en otros programas
 - Palabras clave
 - Descripción de temas de interés y motivación para estar en el programa
 - Marcar campos de conocimiento/líneas de investigación
 - Principales proyectos y/o publicaciones relacionadas con ciencias de la sostenibilidad (máximo 10)
 - Disponible como tutor principal
 - Disponible como miembro de comité tutor
 - Anexos a la tabla de académico, para subir CV y otros documentos
 - Campo de texto para descripción de proyectos vigentes

**Comment by majosesolares** [comment]
Creo que falta la parte de libros y artículos. Anexo el documento que revisamos el otro día.
