### ISSUE TITLE
Entidades

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#70]
Estas son las entidades del Posgrado:

Facultad de Arquitectura
Facultad de Ciencias
Escuela Nacional de Estudios Superiores Unidad León
Escuela Nacional de Estudios Superiores Unidad Morelia
Instituto de Ecología
Instituto de Ciencias del Mar y Limnología
Instituto de Biología
Instituto de Investigaciones Económicas
Instituto de Investigaciones Sociales
Instituto de Investigaciones en Ecosistemas y Sustentabilidad
Instituto de Ingeniería
Instituto de Energías Renovables

**Comment by rgarcia-herrera** [comment]
Cargarlas a la base de datos como Instituciones marcadas como entidad PCS.

**Comment by rgarcia-herrera** [comment]
cab8a9d
