### ISSUE TITLE
En resumen curricular cambiar etiquetas de participaciones en comités

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#81]
Quitar 
Cantidad de comités de nivel maestría en los que participa en el PCS
Cantidad de comités de nivel doctorado en los que participa en el PCS

Agregar al final
Cantidad de participaciones como miembro de comité tutor en el PCS a nivel maestría
Cantidad de participaciones como miembro de comité tutor en el PCS a nivel doctorado

**Comment by majosesolares** [comment]
Invertir el orden de otros programas y reemplazar comité tutor por comités tutorales

**Comment by majosesolares** [comment]
También invertir orden en disponibilidad

**Comment by rgarcia-herrera** [comment]
cad83d0
