### ISSUE TITLE
Falta palomear los campos de conocimiento y lineas de investigación que se relacionan con el académico

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#84]
Marcar los campos de conocimiento y líneas de investigación del Doctorado que se relacionan con sus temas de interés y/o experiencia
Crear tablas por separado (campos de conocimiento y líneas de investigación)
Para mayor información sobre los campos y líneas de investigación consultar el archivo  (agregar hipervínculo)
[Campos y líneas Posgrado Ciencias de la Sostenibilidad.pdf](https://github.com/sostenibilidad-unam/posgrado/files/2233071/Campos.y.lineas.Posgrado.Ciencias.de.la.Sostenibilidad.pdf)

**Comment by rgarcia-herrera** [comment]
04d92ae
