### ISSUE TITLE
Resumen académico

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#88]
Cambiar el orden de cantidad de participaciones como tutor principal primero y miembro de comité después (aplica en todos lados)

**Comment by majosesolares** [comment]
En líneas y campos poner la indicación siguiente:
Marque los campos de conocimiento y líneas de investigación relacionados con los temas  de su interés y/o experiencia para facilitar la búsqueda por parte de los aspirantes y alumnos (use la tecla ctrl+clic para elegir más de uno).

Pasar estos dos recuadros hasta abajo (antes de disponibilidad)

**Comment by rgarcia-herrera** [comment]
bd47dc5
