### ISSUE TITLE
Creación de institución

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#89]
Debe regresarte a formulario de adscripción

**Comment by majosesolares** [comment]
Si no está usted adscrito en alguna de las entidades participantes del Posgrado, elija una marcada como "entidad del PCS" con la que prefiera estar asociado para la comunicación con los representantes en el Comité Académico del Programa, y marque la siguiente casilla.

**Comment by rgarcia-herrera** [comment]
4f9657b
