### ISSUE TITLE
Anexar carta de solicitud al perfil académico

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/siges#99]
Agregar "Anexar carta solicitud en papel membreteado y firmada" 
Agregar liga para descargar lineamientos para su consulta que diga "Lineamientos para el desarrollo y evaluación de proyectos."

**Comment by majosesolares** [comment]
[Linemientos para proyectos Posgrado Ciencias de la Sostenibilidad.pdf](https://github.com/sostenibilidad-unam/posgrado/files/2278987/Linemientos.para.proyectos.Posgrado.Ciencias.de.la.Sostenibilidad.pdf)

**Comment by majosesolares** [comment]
[Formato carta de solicitud acreditación-reacreditación de tutores nvo sistema.docx](https://github.com/sostenibilidad-unam/posgrado/files/2278991/Formato.carta.de.solicitud.acreditacion-reacreditacion.de.tutores.nvo.sistema.docx)

**Comment by rgarcia-herrera** [comment]
e41e60d
